baseURL: "https://www.shaiclub.com"
title: شاي للذّكاء الاصطناعي
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
Copyright: Shai Club · Site built by [Noor](https://www.noor.guru)


minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "Arabic"
    languagedirection: rtl
    weight: 1
    menu:
      main:
        - name: مقالات
          url: categories/مقالات/
          weight: 1
        - name: أخبار
          url: categories/أخبار/
          weight: 2
        - name: من نحن؟
          url: about
          weight: 3
        - name: فريقنا
          url: team
          weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Python & AI Community"
  author: فريق شاي
  hideMeta: false
  # author: ["Me", "You"] # multiple authors

  defaultTheme: light
  disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowToc: false
  TocOpen: false
  #  comments: true
  images: ["shai.png"]

  profileMode:
    enabled: true
    title: >
      شاي للذّكاء الاصطناعي


    imageUrl: "shai.png"
    imageTitle: Shai Club logo
    imageWidth: 400
    imageHeight: 400
    buttons:
      - name: مقالات
        url: categories/مقالات
      - name: أخبار
        url: categories/أخبار
      - name: فريقنا
        url: team

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/company/shaiclub"
    - name: facebook
      url: "https://www.facebook.com/AIClub"
    - name: instagram
      url: "https://instagram.com/shai_club"
    - name: youtube
      url: "https://www.youtube.com/channel/UChrS4q5dnlCdmtucRW-yojQ"
    - name: email
      url: "mailto:ai.juclub@gmail.com"

  label:
    text: شاي للذّكاء الاصطناعي
    icon: /shai.png
    iconHeight: 50

  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"

#  cover:
#    hiddenInList: false # hide on list pages and home
#    hidden: false # hide everywhere but not in structured data
#    hiddenInSingle: false # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series
  team: teams

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true